=== vaclav/zkousec/data/TestingQuestionsFormat.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.w3schools.com/Testovac"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="testing">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="questions" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="question" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="part" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:choice>
                                                    <xs:element name="text" type="xs:string"/>
                                                    <xs:element name="img" type="xs:string"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="answers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="a" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="correct" type="xs:boolean"
                                                                                  default="false"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== vaclav/zkousec/data/sample.xml
<?xml version="1.0"?>

<testing xmlns="http://www.w3schools.com/Testovac"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com/Testovac TestingQuestionsFormat.xsd">
    <id>test 1</id>
    <description>tests for anything and everything</description>
    <version>1</version>
    <questions>
        <question>
            <part>
                <text>Why is the sky not red?</text>
            </part>
            <part>
                <img>a.png</img>
            </part>
            <part>
                <img>b.png</img>
            </part>
            <part>
                <text>Why is the sky not reddish?</text>
            </part>
            <answers>
                <a correct="true">Because it is blue</a>
                <a correct="false">Because it is orange</a>
                <a correct="true">Because it is not red</a>
                <a>Because it is green</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Why is the grass not red?</text>
            </part>
            <answers>
                <a>Because it is blue</a>
                <a>Because it is orange</a>
                <a correct="true">Because it is not red</a>
                <a>Because it is gray</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Another question</text>
            </part>
            <answers>
                <a correct="true">Correct answer</a>
                <a>Incorrect answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 4</text>
            </part>
            <answers>
                <a correct="true">Correct answer</a>
                <a>Incorrect answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 5</text>
            </part>
            <answers>
                <a correct="true">Correct answer</a>
                <a>Incorrect answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 6</text>
            </part>
            <answers>
                <a>Incorrect answer</a>
                <a correct="true">Correct answer</a>
                <a>Incorrect answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 7</text>
            </part>
            <answers>
                <a>Incorrect answer</a>
                <a>Incorrect answer</a>
                <a correct="true">Correct answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 8</text>
            </part>
            <answers>
                <a correct="true">Correct answer</a>
                <a>Incorrect answer</a>
                <a>Incorrect answer</a>
            </answers>
        </question>
        <question>
            <part>
                <text>Question 9</text>
            </part>
            <answers>
                <a>Incorrect answer</a>
                <a correct="true">Correct answer</a>
            </answers>
        </question>
    </questions>
</testing>
